#!/bin/bash

DATASET_DIR=datasets/mmact/videos

FILES=($(find "$DATASET_DIR" -name '*.mp4'))

for file in ${FILES[@]};
do
  echo -n "Converting $file..."
  mv "$file" "$file.fhd"
  ffmpeg -i "$file.fhd" -s 640x360 "$file" &>/dev/null
  echo -e "\e[32mOK\e[0m"
done