modalities:
  acc_phone:
    model:
      class_name: CNN1D
      args:
        - 321
        - 36
    transforms:
      - class_name: Normalize
        from_module: transforms
        in_test: true
        args:
          - [ -0.0659151, -6.96950652, -0.83807499 ]
          - [ 1.83959157, 2.44727826, 2.29080495 ]
      - class_name: Sampler
        from_module: transforms
        in_test: true
        args:
          - 107
      - class_name: Flatten
        from_module: transforms
        in_test: true
        args: [ ]
    learning_rate: 0.0002
    batch_size: 16
    num_epochs: 200
    criterion:
      class_name: CrossEntropyLoss
      from_module: torch.nn
    optimizer:
      class_name: RMSprop
      from_module: torch.optim
  sdfdi:
    model:
      class_name: MobileNetV2
      args:
        - 36
    transforms:
      - class_name: RandomResizedCrop
        from_module: torchvision.transforms
        in_test: false
        args:
          - 480
      - class_name: Resize
        from_module: torchvision.transforms
        in_test: true
        args:
          - 224
      - class_name: ToTensor
        from_module: torchvision.transforms
        in_test: true
        args: [ ]
    learning_rate: 0.0001
    batch_size: 32
    num_epochs: 10
    criterion:
      class_name: CrossEntropyLoss
      from_module: torch.nn
    optimizer:
      class_name: Adam
      from_module: torch.optim

dataset:
  class_name: MmactDataset
  shuffle: true
  train_kwargs:
    subjects: [ 1, 3, 5, 9 ]
    sessions: [ 1, 2, 3, 4, 5 ]
    scenes: [ 1, 2, 3, 4 ]
  validation_kwargs:
    subjects: [ 2, 4 ]
    sessions: [ 1, 2, 3, 4, 5 ]
    scenes: [ 1, 2, 3, 4 ]
  test_kwargs:
    subjects: [ 6, 8 ]
    sessions: [ 1, 2, 3, 4, 5 ]
    scenes: [ 1, 2, 3, 4 ]