# ATTENTION!
# This configuration file is not inheriting from default.yaml
modalities:
  inertial:
    transforms:
      - class_name: Normalize
        from_module: transforms
        in_test: true
        args:
          - [ -1.65804089e-01, -2.88375486e+00,  4.25408345e-01,  5.40047484e+00, -3.81441984e+00, 1.26836780e+00, 2.14082568e-03, -1.77516933e-02, -2.96111521e-02, -4.68627653e-02, 3.90400772e-01, 1.43687585e-01 ]
          - [ 1.73399587, 2.17337823, 2.03517155, 3.7150504, 3.46689411, 2.9703028, 0.64952911, 0.78470781, 0.43690807, 1.15647647, 0.21387406, 1.26683067 ]
      - class_name: Sampler
        from_module: transforms
        in_test: true
        args:
          - 354
      - class_name: Jittering
        from_module: transforms
        in_test: false
        args:
          - [ 0, 500 ]
      - class_name: Flatten
        from_module: transforms
        in_test: true
        args: [ ]
    model:
      class_name: CNN1D
      args: [ ]
      kwargs:
        len_seq: 4248
        norm_out: true
        out_size: 512
        dropout_rate: 0.0
  sdfdi:
    transforms:
      - class_name: RandomResizedCrop
        from_module: torchvision.transforms
        in_test: false
        args:
          - 480
      - class_name: Resize
        from_module: torchvision.transforms
        in_test: true
        args:
          - 224
      - class_name: ToTensor
        from_module: torchvision.transforms
        in_test: true
        args: [ ]
    model:
      class_name: MobileNetV2
      args: [ ]
      kwargs:
        norm_out: true
        out_size: 512
        dropout_rate: 0.0

dataset:
  class_name: MmactDataset
  shuffle: true
  train_kwargs:
    subjects: [ 1, 3, 5, 7, 9 ]
    actions: null
    sessions: [ 1, 2, 3, 4, 5 ]
    scenes: [ 1, 2, 3, 4 ]
  validation_kwargs:
    subjects: [ 2, 4 ]
    actions: null
    sessions: [ 1, 2, 3, 4, 5 ]
    scenes: [ 1, 2, 3, 4 ]
  test_kwargs:
    subjects: [ 6, 8, 10 ]
    actions: null
    sessions: [ 1, 2, 3, 4, 5 ]
    scenes: [ 1, 2, 3, 4 ]

general:
  batch_size: 32
  num_epochs: 500
  num_neighbors: 45
  num_samples: 2
  shuffle: true
  mlp_kwargs:
    input_size: 1024
    out_size: 512
    hidden_size: 2048
    norm_out: true
    dropout_rate: 0.1
  criterion:
    class_name: TripletLossHard
    from_module: losses
    kwargs:
      margin: 0.1
      semi_hard: true
  optimizer:
    class_name: RMSprop
    from_module: torch.optim
    kwargs:
      lr: 0.0001
  scheduler:
    class_name: ReduceLROnPlateau
    from_module: torch.optim.lr_scheduler
    kwargs:
      patience: 10
      verbose: true