dataset:
  num_classes: 27
  # head, left elbow, left hand, right elbow, right hand, left knee, left foot, right knee and right foot
  selected_joints: [0, 5, 7, 9, 11, 13, 15, 17, 19]
  num_frames: 41

training:
  learning_rate: 0.001
  batch_size: 32
  num_epochs: 350

model:
  model_type: 'gru'
  hidden_size: 128
  num_layers: 2