modalities:
  inertial:
    model:
      class_name: CNN1D
      args: [ ]
    transforms:
      - class_name: Normalize
        from_module: transforms
        in_test: true
        args:
          - [ -0.62575306, -0.26179606, -0.07613295, 3.70461374, -4.34395205, -0.09911604 ]
          - [ 0.6440941, 0.46361165, 0.43402348, 87.2470291, 100.86503743, 107.77852571 ]
      - class_name: Sampler
        from_module: transforms
        in_test: true
        args:
          - 107
      - class_name: FilterDimensions
        from_module: transforms
        in_test: true
        args:
          - [ 0, 1, 2 ]
      - class_name: Jittering
        from_module: transforms
        in_test: false
        args:
          - 500
      - class_name: Flatten
        from_module: transforms
        in_test: true
        args: [ ]
    learning_rate: 0.0002
    batch_size: 16
    num_epochs: 200
    criterion:
      class_name: CrossEntropyLoss
      from_module: torch.nn
    optimizer:
      class_name: SGD
      from_module: torch.optim
  sdfdi:
    model:
      class_name: MobileNetV2
      args:
        - 27
    transforms:
      - class_name: RandomResizedCrop
        from_module: torchvision.transforms
        in_test: false
        args:
          - 480
      - class_name: Resize
        from_module: torchvision.transforms
        in_test: true
        args:
          - 224
      - class_name: ToTensor
        from_module: torchvision.transforms
        in_test: true
        args: [ ]
    learning_rate: 0.0001
    batch_size: 32
    num_epochs: 50
    criterion:
      class_name: CrossEntropyLoss
      from_module: torch.nn
    optimizer:
      class_name: Adam
      from_module: torch.optim
  skeleton:
    model:
      class_name: BiLSTM
      args:
        # Input size len(selected_joints) * 3 (x,y,z)
        - 27
        # hidden_size
        - 128
        # num_layers
        - 2
        # num_classes
        - 27
    transforms:
      - class_name: Normalize
        from_module: transforms
        in_test: true
        args:
          - [ -0.09214367,-0.29444627, 2.87122181 ]
          - [ 0.13432376, 0.46162172, 0.12374677 ]
      - class_name: CropToSize
        from_module: transforms
        in_test: true
        args:
          - 41
      - class_name: FilterJoints
        from_module: transforms
        in_test: true
        args:
          - [ 0, 5, 7, 9, 11, 13, 15, 17, 19 ]
      - class_name: RandomEulerRotation
        from_module: transforms
        in_test: true
        args:
          - -10
          - 10
          - 10
      - class_name: ToSequence
        from_module: transforms
        in_test: true
        args:
          - 41
          - 27
    learning_rate: 0.001
    batch_size: 32
    num_epochs: 350
    criterion:
      class_name: CrossEntropyLoss
      from_module: torch.nn
    optimizer:
      class_name: RMSprop
      from_module: torch.optim

dataset:
  class_name: UtdMhadDataset
  shuffle: true
  train_kwargs:
    subjects: [ 1, 3, 5, 7 ]
  validation_kwargs:
    subjects: [ 2, 4 ]
  test_kwargs:
    subjects: [ 6, 8 ]