modalities:
  inertial:
    transforms:
      - class_name: Normalize
        from_module: transforms
        in_test: true
        args:
          - [ -0.62575306, -0.26179606, -0.07613295, 3.70461374, -4.34395205, -0.09911604 ]
          - [ 0.6440941, 0.46361165, 0.43402348, 87.2470291, 100.86503743, 107.77852571 ]
      - class_name: Jittering
        from_module: transforms
        in_test: false
        args:
          - [ 0, 500, 1000 ]
      - class_name: Sampler
        from_module: transforms
        in_test: true
        args:
          - 107
      - class_name: Flatten
        from_module: transforms
        in_test: true
        args: [ ]
    model:
      class_name: CNN1D
      args:
        - 642
  sdfdi:
    transforms:
      - class_name: RandomResizedCrop
        from_module: torchvision.transforms
        in_test: false
        args:
          - 480
      - class_name: Resize
        from_module: torchvision.transforms
        in_test: true
        args:
          - 224
      - class_name: ToTensor
        from_module: torchvision.transforms
        in_test: true
        args: [ ]
    model:
      class_name: MobileNetV2
      args: [ ]
  skeleton:
    transforms:
      - class_name: Normalize
        from_module: transforms
        in_test: true
        args:
          - [ -0.09214367,-0.29444627, 2.87122181 ]
          - [ 0.13432376, 0.46162172, 0.12374677 ]
      - class_name: CropToSize
        from_module: transforms
        in_test: true
        args:
          - 41
      - class_name: FilterJoints
        from_module: transforms
        in_test: true
        args:
          - [ 0, 5, 7, 9, 11, 13, 15, 17, 19 ]
      - class_name: RandomEulerRotation
        from_module: transforms
        in_test: false
        args:
          - -10
          - 10
          - 10
      - class_name: Flatten
        from_module: transforms
        in_test: true
        args: [ ]
    model:
      class_name: CNN1D
      args:
        - 1107

dataset:
  class_name: UtdMhadDataset
  shuffle: true
  train_kwargs:
    subjects: [ 1, 3, 5, 7 ]
    actions: null
  validation_kwargs:
    subjects: [ 2, 4 ]
    actions: null
  test_kwargs:
    subjects: [ 2, 4, 6, 8 ]
    actions: null

general:
  batch_size: 32
  num_samples: 4
  num_epochs: 5
  num_neighbors: 21
  shuffle: true
  mlp_out_size: 512
  model_kwargs:
    out_size: 512
    norm_out: true
  criterion:
    class_name: TripletLossHard
    from_module: losses
    kwargs:
      margin: 0.1
      semi_hard: true
  optimizer:
    class_name: RMSprop
    from_module: torch.optim
    kwargs:
      lr: 0.00001
  scheduler:
    class_name: ReduceLROnPlateau
    from_module: torch.optim.lr_scheduler
    kwargs:
      patience: 10
      verbose: true