modalities:
  inertial:
    num_epochs: 400
    num_neighbors: 21
    num_samples: 4
    batch_size: 32
    model:
      class_name: CNN1D
      args:
        - 321
      kwargs:
        out_size: 512
        norm_out: true
        dropout_rate: 0.1
    criterion:
      class_name: TripletLossHard
      from_module: losses
      kwargs:
        margin: 0.9
        semi_hard: false
    optimizer:
      class_name: RMSprop
      from_module: torch.optim
      kwargs:
        lr: 0.00001
    scheduler:
      class_name: ReduceLROnPlateau
      from_module: torch.optim.lr_scheduler
      kwargs:
        patience: 10
        verbose: true
  sdfdi:
    num_epochs: 310
    num_neighbors: 21
    num_samples: 4
    batch_size: 32
    model:
      class_name: MobileNetV2
      args: [ ]
      kwargs:
        out_size: 512
        norm_out: true
        dropout_rate: 0.1
    criterion:
      class_name: TripletLossHard
      from_module: losses
      kwargs:
        margin: 0.1
        semi_hard: false
    optimizer:
      class_name: Adam
      from_module: torch.optim
      kwargs:
        lr: 0.0001
    scheduler:
      class_name: ReduceLROnPlateau
      from_module: torch.optim.lr_scheduler
      kwargs:
        patience: 10
        verbose: true
  skeleton:
    transforms:
      - class_name: Normalize
        from_module: transforms
        in_test: true
        args:
          - [ -0.09214367,-0.29444627, 2.87122181 ]
          - [ 0.13432376, 0.46162172, 0.12374677 ]
      - class_name: CropToSize
        from_module: transforms
        in_test: true
        args:
          - 41
      - class_name: FilterJoints
        from_module: transforms
        in_test: true
        args:
          - [ 0, 5, 7, 9, 11, 13, 15, 17, 19 ]
      - class_name: RandomEulerRotation
        from_module: transforms
        in_test: false
        args:
          - -10
          - 10
          - 10
      - class_name: Flatten
        from_module: transforms
        in_test: true
        args: [ ]
    num_epochs: 400
    num_neighbors: 21
    num_samples: 4
    batch_size: 32
    model:
      class_name: CNN1D
      args:
        - 1107
      kwargs:
        out_size: 512
        norm_out: true
        dropout_rate: 0.1
    criterion:
      class_name: TripletLossHard
      from_module: losses
      kwargs:
        margin: 0.9
        semi_hard: false
    optimizer:
      class_name: RMSprop
      from_module: torch.optim
      kwargs:
        lr: 0.00001
    scheduler:
      class_name: ReduceLROnPlateau
      from_module: torch.optim.lr_scheduler
      kwargs:
        patience: 10
        verbose: true