modalities:
  inertial:
    transforms:
      - class_name: Normalize
        from_module: transforms
        in_test: true
        args:
          - [ -0.62575306, -0.26179606, -0.07613295, 3.70461374, -4.34395205, -0.09911604 ]
          - [ 0.6440941, 0.46361165, 0.43402348, 87.2470291, 100.86503743, 107.77852571 ]
      - class_name: Jittering
        from_module: transforms
        in_test: false
        args:
          - [ 0, 500, 1000 ]
      - class_name: Sampler
        from_module: transforms
        in_test: true
        args:
          - 107
      - class_name: Flatten
        from_module: transforms
        in_test: true
        args: [ ]
    learning_rate: 0.0001
    num_epochs: 100
    num_neighbors: 4
    num_samples: 4
    batch_size: 32
    model:
      class_name: CNN1D
      args:
        - 642
      kwargs:
        out_size: 128
        norm_out: true
    criterion:
      class_name: TripletLossHard
      from_module: losses
      kwargs:
        margin: 0.1
        semi_hard: true
    optimizer:
      class_name: RMSprop
      from_module: torch.optim
  sdfdi:
    learning_rate: 0.0001
    num_epochs: 100
    num_neighbors: 20
    num_samples: 4
    batch_size: 32
    model:
      class_name: MobileNetV2
      args:
        - 128
      kwargs: {}
    criterion:
      class_name: TripletLossHard
      from_module: losses
      kwargs:
        margin: 0.1
        semi_hard: true
    optimizer:
      class_name: RMSprop
      from_module: torch.optim
  skeleton:
    transforms:
      - class_name: Normalize
        from_module: transforms
        in_test: true
        args:
          - [ -0.09214367,-0.29444627, 2.87122181 ]
          - [ 0.13432376, 0.46162172, 0.12374677 ]
      - class_name: CropToSize
        from_module: transforms
        in_test: true
        args:
          - 41
      - class_name: FilterJoints
        from_module: transforms
        in_test: true
        args:
          - [ 0, 5, 7, 9, 11, 13, 15, 17, 19 ]
      - class_name: RandomEulerRotation
        from_module: transforms
        in_test: true
        args:
          - -10
          - 10
          - 10
      - class_name: Flatten
        from_module: transforms
        in_test: true
        args: [ ]
    learning_rate: 0.0001
    num_epochs: 100
    num_neighbors: 21
    num_samples: 4
    batch_size: 32
    model:
      class_name: CNN1D
      args:
        - 1107
      kwargs:
        out_size: 128
        norm_out: true
    criterion:
      class_name: TripletLossHard
      from_module: losses
      kwargs:
        margin: 0.1
        semi_hard: true
    optimizer:
      class_name: RMSprop
      from_module: torch.optim